const CardsHints = {
  "1_clubs": { en: "", ar: "" },
  "2_clubs": {
    en: `how many rules say "do not talk about Fight Club"`,
    ar: "",
  },
  "3_clubs": { en: "", ar: "" },
  "4_clubs": { en: "", ar: "" },
  "5_clubs": { en: "", ar: "" },
  "6_clubs": { en: "", ar: "" },
  "7_clubs": { en: "", ar: "" },
  "8_clubs": { en: "", ar: "" },
  "9_clubs": { en: "", ar: "" },
  "10_clubs": { en: "", ar: "" },
  "1_spades": { en: "", ar: "" },
  "2_spades": { en: "", ar: "" },
  "3_spades": { en: "", ar: "" },
  "4_spades": { en: "", ar: "" },
  "5_spades": { en: "", ar: "" },
  "6_spades": { en: "", ar: "" },
  "7_spades": { en: "", ar: "" },
  "8_spades": { en: "", ar: "" },
  "9_spades": { en: "", ar: "" },
  "10_spades": { en: "", ar: "" },
  "1_diamonds": { en: "", ar: "" },
  "2_diamonds": { en: "", ar: "" },
  "3_diamonds": { en: "", ar: "" },
  "4_diamonds": { en: "", ar: "" },
  "5_diamonds": { en: "", ar: "" },
  "6_diamonds": { en: "", ar: "" },
  "7_diamonds": { en: "", ar: "" },
  "8_diamonds": { en: "I keep my Jewelry in a sand clock", ar: "" },
  "9_diamonds": { en: "", ar: "" },
  "10_diamonds": { en: "", ar: "" },
  "1_hearts": { en: "", ar: "" },
  "2_hearts": { en: "", ar: "" },
  "3_hearts": { en: "", ar: "" },
  "4_hearts": { en: "All year seasons are have feelings", ar: "" },
  "5_hearts": { en: "", ar: "" },
  "6_hearts": { en: "", ar: "" },
  "7_hearts": { en: "You hurt my feelings with a rainbow", ar: "" },
  "8_hearts": { en: "", ar: "" },
  "9_hearts": { en: "", ar: "" },
  "10_hearts": { en: "", ar: "" },
  king_clubs: { en: "", ar: "" },
  king_spades: { en: "", ar: "" },
  king_diamonds: { en: "", ar: "" },
  king_hearts: { en: "", ar: "" },
  jack_clubs: { en: "", ar: "" },
  jack_spades: { en: "", ar: "" },
  jack_diamonds: { en: "", ar: "" },
  jack_hearts: { en: "", ar: "" },
  queen_clubs: { en: "", ar: "" },
  queen_spades: { en: "", ar: "" },
  queen_diamonds: { en: "", ar: "" },
  queen_hearts: { en: "", ar: "" },
  colored_jocker: { en: "", ar: "" },
  black_jocker: { en: "", ar: "" },
};

export default CardsHints;
